# Underwriting Service Configuration
server.port=8083
originationServiceURL=http://localhost:8082/api/v1

# ActiveMQ JMS Queue Destination Configuration
freddie.underwriting.jms.destination=freddie.underwriting.events

# Sailpoint & TAM Security Integration Properties
edAdaptorAuthId=sailpoint_user_id
edAdaptorAuthPwd=sailpoint_password
tamCredFileLoc=/config/tam_credentials.properties
macVaultKeyFilePath=/config/macvault.key
isApiMacVaultEnable=true
