server.port=8086
spring.application.name=notification-service

### DATASOURCE (POSTGRESQL DB: freddie_customer)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/freddie_customer}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

### JPA
spring.datasource.tomcat.max-active=10
spring.datasource.tomcat.initial-size=1
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=freddie_customer
spring.jpa.properties.hibernate.format_sql=false

### LOGGING
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

macVault.auth.enable=true
macVault.path=/pkgs/secrets/app/
superUser=${SUPER_USER:freddie_admin_user}

### ACTUATOR
management.endpoints.enabled-by-default=true
management.endpoint.health.show-details=ALWAYS
management.endpoints.web.exposure.include=health, info, metrics
management.endpoints.web.base-path=/actuator

server.session.timeout=600000
server.tomcat.connectionTimeout=-1

bypassPingAuth=true

#Ping token attribute for external
ping.external.token.key=FMACJWT
#Ping token attribute for internal
ping.internal.token.key=FHLMCJWT
#Ping external JWKS URL for token verification
ping.external.jwks.url=https://securedev.fhlmc.com/pa/authtoken/JWKS
#Ping internal JWKS URL for token verification
ping.internal.jwks.url=https://securedev.fhlmc.com/pa/authtoken/JWKS
#ROPC token key
ropc.token.key=Authorization
#ROPC JWKS URL for token verification
ropc.jwks.url=https://authdev.fhlmc.com/ext/fhlmc/JWKS
jwks.cached=true
db.cred.file.location=/etc/app/dbcred
enable.hashicorp.db=true

#AMQ settings
spring.activemq.broker-url=vm://localhost?broker.persistent=false
spring.activemq.user=${ACTIVEMQ_USER:freddie_amq_user}
spring.activemq.queue-name=${ACTIVEMQ_QUEUE:FREDDIE-LOAN-NOTIFICATION-QUEUE.local}
spring.activemq.in-memory=true
spring.activemq.pool.enabled=false
hashicorp.ad.amq.path=/etc/app/amqcred
broker=FREDDIE_ACTIVE_MQ
spring.activemq.redelivery-policy.maximum-redeliveries=5
spring.activemq.redelivery-policy.redelivery-delay=2000
