spring.application.name=loan-origination-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.pool-name=LoanHikariPool

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=freddie_loans

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/freddie-platform

server.port=8082

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

feign.circuitbreaker.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0

logging.level.com.freddieapp.loanorigination=INFO

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

