server.port=8088
spring.application.name=login-frontend-service

# PostgreSQL Database 1 Connection: User Account Details & Profiles (freddie_customer)
spring.datasource.url=jdbc:postgresql://localhost:5432/freddie_customer
spring.datasource.username=freddie_admin
spring.datasource.password=freddie_secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=freddie_customer
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Fallback H2 configuration for local unit testing
spring.datasource.continue-on-error=true
