spring.application.name=rate-calculator-service
server.port=8090

bypassPingAuth=false
email.notification.enabled=true
email.notification.host=smtp.freddiemac.com
email.notification.port=587
email.notification.from-address=no-reply@freddiemac.com
